### PR TITLE
Add keyword argument to control overwriting behavior of the decrypter

### PR DESCRIPTION
**Pull request by AhmedAhmedEG**
The overwriting behavior is not exposed from the keyword arguments, I added a --overwrite argument to exactly do that.

### CODE REVIEW

**Comment by uuksu** [comment]
Hey and sorry for taking so long time to react. Your change seems good to me, but I would like to see the flag also implemented in the GUI so that both programs are equal. It could be implemented as a optional checkbox somewhere. If you can do this, I'll merge you PR.

**Comment by AhmedAhmedEG** [comment]
Ok, I will try so.

**Comment by AhmedAhmedEG** [comment]
Ok, I did it, I modified the Gui project and added a checkbox for the overwriting, and tested it and it works, also the IDE automatically did grammar corrects to the texts used in the GUI that was there already, so this makes it even better.

**Comment by uuksu** [comment]
That's perfect, thank you! I'll merge your PR now.

**Pull request merged**
